In [3]:
import numpy as np 

data_1 = [1.0, 3.5, 4.7, -5.1]
arr_1 = np.array(data_1)
print(arr_1)


[ 1.   3.5  4.7 -5.1]


In [11]:
# Indexing

print(arr_1[1])
print(arr_1[2:4])

3.5
[ 4.7 -5.1]


In [3]:
# Multiplication d'un vecteur par un scalaire (ou facteur)
2.0 * arr_1

[  2.    7.    9.4 -10.2]


In [6]:
# Addition d'un float
arr_1 + 3.1

array([ 4.1,  6.6,  7.8, -2. ])

In [9]:
random_arr = np.random.randn(5)
print(random_arr)

[-0.61732833  0.06293965 -1.08588741  1.27252341  0.41699355]


In [5]:
# Mask
random_arr[random_arr > 0]

array([1.19875196, 0.14758767])

In [6]:
random_arr > 0

array([False, False,  True,  True, False])

In [10]:
random_arr[random_arr < 0] = 0
print(random_arr)

[0.         0.06293965 0.         1.27252341 0.41699355]


Exercice

In [ ]:
# A l'aide de la méthode .arange(), créer un vecteur avec les 7 premiers entiers