In [2]:
## Créer un ndarray de taille 3*2 (3 lignes, 2 colonnes)
import numpy as np 
data = [
    [-10, -5],
    [-1, 2],
    [6, 11]
]

arr_1 = np.array(data)

arr_1

array([[-10,  -5],
       [ -1,   2],
       [  6,  11]])

In [2]:
# Format d'un array
arr_1.shape

(3, 2)

In [3]:
# Que se passe-t-il si on additionne un array avec un nombre (int) ? 
arr_1 + 4

array([[-6, -1],
       [ 3,  6],
       [10, 15]])

In [4]:
# créer un nouvel array dont chacun des éléments est multiplié par 3
arr_1 * 3

array([[-30, -15],
       [ -3,   6],
       [ 18,  33]])

In [5]:
# Appliquer un masque simple
arr_1[arr_1 > 3] = 0
arr_1

array([[-10,  -5],
       [ -1,   2],
       [  0,   0]])

Exercice

In [3]:
# A l'aide de la méthode .arange(), créer une matrice de 3 lignes et 6 colonnes allant de 0 à 17
np.arange(18).reshape(3,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])